{% set version = "1.11.0" %}
{% set build = 3 %}

# Set CUDA related variables
{% if (win64 or linux64) and cuda_compiler_version != "None" %}
  {% set use_cuda = "ON" %}
  {% set cuda_build_prefix = "cuda" + cuda_compiler_version|string %}
{% else %}
  {% set use_cuda = "OFF" %}
  {% set cuda_build_prefix = "" %}
{% endif %}

# Set FFT related variables
{% if win or osx or linux32 or linux64 %}
  {% set use_mkl = "ON" %}
  {% set libfft = "mkl-devel" %}
  {% set pyfft = "mkl_fft" %}
{% else %}
  {% set use_mkl = "OFF" %}
  {% set libfft = "nomkl" %}
  {% set pyfft = "nomkl" %}
{% endif %}

# Set OpenCV related variables
{% set use_opencv = "OFF" %}

package:
    name: tomopy
    version: {{ version }}

source:
  - url: https://github.com/tomopy/tomopy/archive/refs/tags/{{ version }}.tar.gz
    sha256: 105ef5ea184413e7e6d5ab538a60de1831e2b6b63774d2cedd50192113c091ea
    # There is a special alpha release for only tomopy, so it does not make
    # sense to dynamically link to PTL from a shared library
  - url: https://github.com/jrmadsen/PTL/archive/refs/tags/tomopy-v1.0.tar.gz
    sha256: 2fa6b5f8e9e63aa0e9c4e933eadc216e32b13cc6388a15bc3f8fb369757417f2
    folder: source/PTL

build:
  number: {{ build }}
  string: "{{ cuda_build_prefix }}py{{ py }}h{{ PKG_HASH }}_{{ build }}"
  skip: true  # [py2k or (win64 and cuda_compiler_version != "None")]
  script:
    {{ PYTHON }} -m pip install .
    --no-deps --ignore-installed --no-index --no-cache-dir -vv
    --install-option="--"
    --install-option="-GNinja"
    --install-option="-DCMAKE_BUILD_TYPE=Release"
    --install-option="-DTOMOPY_USE_CUDA:BOOL={{ use_cuda }}"
    --install-option="-DTOMOPY_USE_MKL:BOOL={{ use_mkl }}"
    --install-option="-DTOMOPY_USE_OPENCV:BOOL={{ use_opencv }}"
    --install-option="--"
    --install-option="-j{{ CPU_COUNT }}"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [(win64 or linux64) and cuda_compiler_version != "None"]
    - cmake
    - ninja
  host:
    - pip
    - python
    - {{ libfft }}
    - {{ pyfft }}
    - scikit-build >=0.10.1
    - setuptools >=45
    - setuptools_scm >=6.2
    - setuptools_scm_git_archive
  run:
    - {{ pyfft }}
    - numexpr
    - numpy >1.12,<1.22.4
    - pywavelets
    - python
    - scikit-image
    - scipy
    # setuptools required for pkg_resources until next release
    # when importlib_metadata is backport for python<3.8
    - setuptools
    - tifffile
  run_constrained:
    - astra-toolbox >1.8

test:
  requires:
    - pytest
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.prep
    - tomopy.recon
    - tomopy.sim
    - tomopy.util
  source_files:
    - test/*
  commands:
    - unset CUDA_VERSION   # [unix]
    - set "CUDA_VERSION="  # [win]
    - pytest test -vs

app:
    own_environment: True

about:
    home: http://tomopy.readthedocs.io
    license: BSD-3-Clause AND MIT
    license_family: BSD
    license_file:
      - LICENSE.txt
      - source/PTL/LICENSE
    summary: 'Tomographic reconstruction in Python.'
    description: |
      TomoPy is an open-source Python package for tomographic data
      processing and image reconstruction.
    doc_url: http://tomopy.readthedocs.io
    dev_url: https://github.com/tomopy/tomopy

extra:
    recipe-maintainers:
        - tomopy/admins
        - dgursoy
        - decarlof
        - licode
        - ravescovi
        - tacaswell
        - oleksandr-pavlyk
        - carterbox
