{% set version = "1.2.1" %}

package:
    name: tomopy
    version: {{ version }}

source:
    url: https://github.com/tomopy/tomopy/archive/{{ version }}.tar.gz
    fn: tomopy-{{ version }}.tar.gz
    sha256: ee46b2f602bbdb6d0da8640e24e176bcfd8b86f9c47c136b884ab77932ae9d6e

build:
  number: 1
  skip: true  # [win and py2k]
  script:
    - "{{ PYTHON }} build.py"
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - Make  # [win]
    - MinGW  # [win]
    - mkl-devel
  host:
    - pip
    - python={{ python }}
    - setuptools
  run:
    - dxchange
    - futures  # [py2k]
    - numexpr
    - mkl
    - mkl_fft
    - python={{ python }}
    - numpy
    - scikit-image
    - scipy
    - six

test:
  requires:
    - nose
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.prep
    - tomopy.recon
    - tomopy.sim
    - tomopy.util
  source_files:
    - test/*
  commands:
    - nosetests test

app:
    own_environment: True

about:
    home: http://tomopy.readthedocs.io
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: 'Tomographic reconstruction in Python.'

extra:
    recipe-maintainers:
        - dgursoy
        - decarlof
        - licode
        - ravescovi
        - tacaswell
        - oleksandr-pavlyk
