{% set version = "1.4.0" %}

package:
    name: tomopy
    version: {{ version }}

source:
    url: https://github.com/tomopy/tomopy/archive/{{ version }}.tar.gz
    fn: tomopy-{{ version }}.tar.gz
    sha256: d4697f545ff7fa9e76306e72a6b452e0de9840a49a72fe2a4ec65e79c7c90e09

build:
  number: 0
  skip: true  # [win and py2k]
  script:
    - "{{ PYTHON }} build.py"
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - Make  # [win]
    - MinGW  # [win]
    - mkl-devel  # Must not be in host to prevent dependency conflict
    - python={{ python }}  # [win]
  host:
    - pip
    - python={{ python }}
    - setuptools
  run:
    - dxchange
    - futures  # [py2k]
    - numexpr
    - mkl
    - mkl_fft
    - python={{ python }}
    - numpy
    - scikit-image
    - scipy
    - six

test:
  requires:
    - nose
  imports:
    - tomopy
    - tomopy.misc
    - tomopy.prep
    - tomopy.recon
    - tomopy.sim
    - tomopy.util
  source_files:
    - test/*
  commands:
    - nosetests test

app:
    own_environment: True

about:
    home: http://tomopy.readthedocs.io
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: 'Tomographic reconstruction in Python.'

extra:
    recipe-maintainers:
        - dgursoy
        - decarlof
        - licode
        - ravescovi
        - tacaswell
        - oleksandr-pavlyk
