{% set version = "1.12.1" %}
{% set build = 1 %}

# Set CUDA related variables
{% if cuda_compiler_version is not defined or cuda_compiler_version == "None" %}
  {% set use_cuda = "OFF" %}
  {% set cuda_build_prefix = "" %}
  {% set cuda_build_post = build %}
{% else %}
  {% set use_cuda = "ON" %}
  {% set cuda_build_prefix = "cuda" + cuda_compiler_version|string %}
  {% set cuda_build_post = build + 100 %}
{% endif %}

# Set FFT related variables
{% if win or osx or linux32 or linux64 %}
  {% set use_mkl = "ON" %}
  {% set libfft = "mkl-devel" %}
  {% set pyfft = "mkl_fft" %}
{% else %}
  {% set use_mkl = "OFF" %}
  {% set libfft = "nomkl" %}
  {% set pyfft = "nomkl" %}
{% endif %}

# Set OpenCV related variables
{% set use_opencv = "OFF" %}

package:
    name: libtomo
    version: {{ version }}

source:
  - url: https://github.com/tomopy/tomopy/archive/refs/tags/{{ version }}.tar.gz
    sha256: bfdd382e32fac5649cfae8f7aafc70d0a79ff28dd363a834f65c27cf5f530267
    patches:
      - shared-cuda-npp.patch
    # There is a special alpha release for only tomopy, so it does not make
    # sense to dynamically link to PTL from a shared library
  - url: https://github.com/jrmadsen/PTL/archive/refs/tags/tomopy-v1.0.tar.gz
    sha256: 2fa6b5f8e9e63aa0e9c4e933eadc216e32b13cc6388a15bc3f8fb369757417f2
    folder: source/PTL

build:
  number: {{ build }}
  skip: True  # [win and (cuda_compiler_version != "None")]

app:
    own_environment: True

outputs:
  - name: libtomo
    script: build-cxx.sh  # [unix]
    script: bld-cxx.bat   # [win]
    build:
      string: "{{ cuda_build_prefix }}h{{ PKG_HASH }}_{{ cuda_build_post }}"
      script_env:
        - USE_CUDA={{ use_cuda }}
        - USE_MKL={{ use_mkl }}
        - USE_OPENCV={{ use_opencv }}
      run_exports:
        - {{ pin_subpackage('libtomo') }}
      track_features:
        - nocuda_CmNhJ1DLKR  # [cuda_compiler_version == "None"]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
        - cmake >=3.17
        - ninja
      host:
        - {{ libfft }}
      run:
        - __cuda  # [cuda_compiler_version != "None"]
      run_constrained:
        - tomopy >1.11.0  # tomopy split into two packages
    test:
      commands:
        - test -f $PREFIX/lib/libtomo-recon$SHLIB_EXT  # [unix]
        - test -f $PREFIX/include/libtomo/recon.h  # [unix]
        - test -f $PREFIX/lib/cmake/libtomo/libtomoTargets.cmake  # [unix]
        - if not exist %LIBRARY_LIB%\\tomo-recon.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\tomo-recon.dll exit 1  # [win]
        - if not exist %LIBRARY_INC%\\libtomo\\recon.h exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\cmake\\libtomo\\libtomoTargets.cmake exit 1  # [win]

  - name: tomopy
    script: build-python.sh  # [unix]
    script: bld-python.bat   # [win]
    build:
      noarch: python
      script_env:
        - SETUPTOOLS_SCM_PRETEND_VERSION={{ PKG_VERSION }}
    requirements:
      host:
        - pip
        - python >=3.6,<4
        - setuptools >=45
        - setuptools_scm >=6.2
        - setuptools_scm_git_archive
      run:
        - {{ pin_subpackage('libtomo') }}
        - {{ pyfft }}
        - importlib_metadata
        - numexpr =2.*
        - numpy >1.12,!=1.22.4
        - pywavelets =1.*
        - python >=3.6,<4
        - scikit-image >=0.17,<1
        - scipy =1.*
        - tifffile >=2019
      run_constrained:
        - astra-toolbox >1.8,<3
    test:
      requires:
        - pip
        - pytest
      imports:
        - tomopy
        - tomopy.misc
        - tomopy.prep
        - tomopy.recon
        - tomopy.sim
        - tomopy.util
      source_files:
        - test/*
      commands:
        - pip check
        - unset CUDA_VERSION   # [unix]
        - set "CUDA_VERSION="  # [win]
        - pytest test -vs

about:
    home: http://tomopy.readthedocs.io
    license: BSD-3-Clause AND MIT
    license_family: BSD
    license_file:
      - LICENSE.txt
      - source/PTL/LICENSE
    summary: 'Tomographic reconstruction in Python.'
    description: >
      TomoPy is an open-source Python package for tomographic data
      processing and image reconstruction.
    doc_url: http://tomopy.readthedocs.io
    dev_url: https://github.com/tomopy/tomopy

extra:
    recipe-maintainers:
        - tomopy/admins
        - dgursoy
        - decarlof
        - licode
        - ravescovi
        - tacaswell
        - oleksandr-pavlyk
        - carterbox
